from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required, user_passes_test
import csv
from reportlab.pdfgen import canvas
from attendance.models import AttendanceRecord

def is_admin(user):
    return user.role == 'admin' or user.is_superuser

@login_required
def export_attendance_csv(request):
    # Determine who can access this: Admin or Teacher
    if not (request.user.is_superuser or request.user.role == 'teacher' or request.user.role == 'admin'):
         return HttpResponse("Unauthorized", status=403)

    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="attendance_report.csv"'

    writer = csv.writer(response)
    writer.writerow(['Student', 'Course', 'Date', 'Status', 'Timestamp'])

    if request.user.role == 'teacher':
        records = AttendanceRecord.objects.filter(session__course__teacher=request.user)
    else:
        # Admin gets everything
        records = AttendanceRecord.objects.all()

    records = records.select_related('student', 'session', 'session__course')
    
    for record in records:
        writer.writerow([
            record.student.username,
            record.session.course.code,
            record.session.date,
            record.status,
            record.timestamp
        ])

    return response

@login_required
def export_attendance_pdf(request):
    # Determine who can access this: Admin or Teacher
    if not (request.user.is_superuser or request.user.role == 'teacher' or request.user.role == 'admin'):
         return HttpResponse("Unauthorized", status=403)

    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename="attendance_report.pdf"'

    p = canvas.Canvas(response)
    p.setFont("Helvetica-Bold", 16)
    p.drawString(50, 800, "Attendance Report")
    
    p.setFont("Helvetica", 12)
    p.drawString(50, 780, f"Generated by: {request.user.username}")
    
    y = 750
    p.setFont("Helvetica", 10)
    
    if request.user.role == 'teacher':
        records = AttendanceRecord.objects.filter(session__course__teacher=request.user)
    else:
        records = AttendanceRecord.objects.all()

    records = records.select_related('student', 'session', 'session__course').order_by('-timestamp')[:100] # Limit for demo
    
    # Header
    p.drawString(50, y, "Student")
    p.drawString(200, y, "Course")
    p.drawString(300, y, "Date")
    p.drawString(400, y, "Status")
    y -= 20
    p.line(50, y+15, 500, y+15)
    
    for record in records:
        text_student = f"{record.student.username}"
        text_course = f"{record.session.course.code}"
        text_date = f"{record.session.date}"
        text_status = f"{record.status}"
        
        p.drawString(50, y, text_student)
        p.drawString(200, y, text_course)
        p.drawString(300, y, text_date)
        p.drawString(400, y, text_status)
        
        y -= 20
        if y < 50:
            p.showPage()
            y = 800
            
    p.showPage()
    p.save()
    return response

@login_required
def export_single_session_pdf(request, session_id):
    if not (request.user.is_superuser or request.user.role == 'teacher' or request.user.role == 'admin'):
         return HttpResponse("Unauthorized", status=403)
         
    session = get_object_or_404(Session, pk=session_id)
    if not request.user.is_superuser and request.user.role == 'teacher' and session.course.teacher != request.user:
         return HttpResponse("Unauthorized for this course", status=403)

    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = f'attachment; filename="attendance_session_{session.id}.pdf"'

    p = canvas.Canvas(response)
    p.setFont("Helvetica-Bold", 16)
    p.drawString(50, 800, f"Attendance Certificate - {session.course.name}")
    
    p.setFont("Helvetica", 11)
    p.drawString(50, 770, f"Date: {session.date} | Time: {session.start_time} - {session.end_time}")
    p.drawString(50, 755, f"Teacher: {session.course.teacher.get_full_name()}")
    
    y = 720
    p.setFont("Helvetica-Bold", 11)
    p.drawString(50, y, "Student Name / Username")
    p.drawString(300, y, "Student ID")
    p.drawString(450, y, "Status")
    y -= 15
    p.line(50, y+10, 550, y+10)
    
    records = AttendanceRecord.objects.filter(session=session).select_related('student')
    p.setFont("Helvetica", 10)
    
    for record in records:
        y -= 20
        p.drawString(50, y, record.student.get_full_name() or record.student.username)
        p.drawString(300, y, record.student.student_id or "N/A")
        p.drawString(450, y, "PRESENT")
        
        if y < 50:
            p.showPage()
            y = 750

    p.showPage()
    p.save()
    return response
